version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/*"
    allow:
      - dependency-type: "development"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
