version: '3'
services:
  mongo:
    image: mongo:3.4-xenial
    ports:
      - "27017"
#  mongo-test:
#    image: mongo:3.4-xenial
#    links:
#      - mongo
#    depends_on:
#      - mongo
#    command: mongo test
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200"
#     - "9300"
  uwazi:
    build:
      context: .
      dockerfile: Dockerfile-devshell
    volumes:
      - .:/root/uwazi:Z,rw
    links:
      - mongo
      - elasticsearch
    ports:
      - "3000"
      - "8080"
    depends_on:
      - mongo
      - elasticsearch
