version: '3'
services:
  mongo:
    image: mongo:3.4-xenial
    ports:
      - "27017"
    networks:
      - uwazi_network
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200"
    networks:
      - uwazi_network
  uwazi:
    build:
      context: .
      dockerfile: Dockerfile-devshell
    volumes:
      - .:/root/uwazi:Z,rw
    ports:
      - "3000"
      - "8080"
    networks:
      uwazi_network:
        aliases:
          - uwazi.localdomain
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - DBHOST=mongo
      - DATABASE_NAME=uwazi_development
      - DOMAIN=uwazi.localdomain
      - ELASTICSEARCH_URL=http://elasticsearch:9200
networks:
  uwazi_network:
