export enum PXErrorCode {
  SEGMENTATIONS_UNAVAILABLE = 'SEGMENTATIONS_UNAVAILABLE',
  LANGUAGE_NOT_FOUND = 'LANGUAGE_NOT_FOUND',
  EXTRACTOR_NOT_FOUND = 'EXTRACTOR_NOT_FOUND',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  TARGET_TEMPLATE_NOT_FOUND = 'TARGET_TEMPLATE_NOT_FOUND',
  SOURCE_TEMPLATE_NOT_FOUND = 'SOURCE_TEMPLATE_NOT_FOUND',
  TARGET_TEMPLATE_INVALID = 'TARGET_TEMPLATE_INVALID',
  ENTITY_INVALID = 'ENTITY_INVALID',
  TARGET_SOURCE_TEMPLATE_EQUAL = 'TARGET_SOURCE_TEMPLATE_EQUAL',
}

export class PXValidationError extends Error {
  constructor(
    public code: PXErrorCode,
    message: string,
    options?: ErrorOptions
  ) {
    super(message, options);
    this.name = 'PXValidationError';
  }
}
