name: check translations

on:
  push:
    branches:
      - master
      - development
      - release
  pull_request:

jobs:
  check_translations:
    runs-on: ubuntu-18.04
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0-amd64
        ports:
          - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      mongodb:
        image: mongo:4.2.6
        ports:
          - 27017/tcp
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.3'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn blank-state
        env:
          DBHOST: localhost:${{ job.services.mongodb.ports[27017] }}
          ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
      - run: yarn check-translations
        env:
          DBHOST: localhost:${{ job.services.mongodb.ports[27017] }}
