name: Codeclimate

on:
  workflow_run:
    workflows: ["App unit tests", "API unit tests"]
    types:
      - completed

jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - name: Download tests results
        uses: actions/download-artifact@v3
      - name: Download codeclimate binay
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - name: Sum coverage reports
        run: ./cc-test-reporter sum-coverage codeclimate.*.json -p 2 -o codeclimate.total.json
      - name: Upload coverage reports
        run: ./cc-test-reporter upload-coverage -i codeclimate.total.json
